package exploration.model.enumerations;

public enum AttributeEnum {

	MAX_QUERY_SIZE,
	MIN_SUPPORT,
	MIN_SUPPORT_AFTER_UPDATE,
	PRESERVE_ORDER,
	NEIGHBORS,
	USER_SIMILARITY,
	RECOMMENDER,
	USER_NEIGHBORHOOD,
	PERFORMANCE_THRESHOLD,
	FP_WEIGHT,
	BETA_EFFICIENCY,
	MIN_PRECISION,
	MIN_SUPPORT_SVM,
	MAX_NUMBER_OF_QUERIES,
	POWER,
	MIN_WEIGHT,
	HITS_PER_PAGE,
	QUERY_SUBMISSION_PER_UNIT_TIME,
	QUERY_TIME_CONSUMED,
	IE_SUBMISSION_PER_TIME,
	IE_TIME_CONSUMED,
	FOLDS,
	MINIMUM_INSTANCE_WEIGHT,
	OPTIMIZATION_RUNS,
	SEED_VALUE,
	USE_PRUNING,
	CHECK_ERROR_RATE;
	
}
