package exploration.model.enumerations;

public enum ContentExtractionSystemEnum {
	
	GOOGLE_CONTENT_EXTRACTOR, TIKA_CONTENT_EXTRACTOR, DUMMY_CONTENT_EXTRACTOR, LYNX_CONTENT_EXTRACTOR, SGML_CONTENT_EXTRACTOR

}
