package exploration.model.enumerations;

public enum ExperimentEnum {
	QUERYING, CONSISTENSY_1, CONSISTENSY_2, CONSISTENSY_3, CONSISTENSY_4, CONSISTENSY_5, CONSISTENSY_6,
	NEGATIVE_CONSISTENSY_1, NEGATIVE_CONSISTENSY_2, NEGATIVE_CONSISTENSY_3, NEGATIVE_CONSISTENSY_4, NEGATIVE_CONSISTENSY_5, TUPLE_CONSISTENCY;

}
