package exploration.model.enumerations;

public enum SampleGeneratorEnum {

	SIMPLE, //1
	GLOBAL_SAME_CARDINALITY, //2
	CLUSTER_SAME_CARDINALITY, //3
	GLOBAL_PROPORTIONAL, //4
	CLUSTER_PROPORTIONAL, //5
	RR_GLOBAL_SAME_CARDINALITY, //6
	RR_CLUSTER_SAME_CARDINALITY, //7
	RR_GLOBAL_PROPORTIONAL, //8
	RR_CLUSTER_PROPORTIONAL, //9
	ANY, 
	CLUSTER_CLOSENESS_SAME_CARDINALITY,//10
	CLUSTER_CLOSENESS_PROPORTIONAL,//11
	RR_CLUSTER_CLOSENESS_SAME_CARDINALITY,//12
	RR_CLUSTER_CLOSENESS_PROPORTIONAL;//13
	
}
