package exploration.model.enumerations;

public enum SampleAlgorithmEnum {

	RELATIONS_SVM,
	RELATIONS_SVM_TASW,
	RULES,
	RULES_TASW,
	TUPLES_10,
	TUPLES_10_NO_LARGE_DOMAIN,
	TUPLES_10_NO_SMALL_DOMAIN,
	TUPLES_20,
	TUPLES_20_NO_LARGE_DOMAIN,
	TUPLES_20_NO_SMALL_DOMAIN,
	TUPLES_30,
	TUPLES_30_NO_LARGE_DOMAIN,
	TUPLES_30_NO_SMALL_DOMAIN,
	TUPLES_40,
	TUPLES_40_NO_LARGE_DOMAIN,
	TUPLES_40_NO_SMALL_DOMAIN,
	TUPLES_50,
	TUPLES_50_NO_LARGE_DOMAIN,
	TUPLES_50_NO_SMALL_DOMAIN,
	RELATIONS_IG,
	RELATIONS_IG_TASW,
	RELATIONS_CHI2,
	RELATIONS_CHI2_TASW,
	SIGNIFICANT_PHRASES,
	SIGNIFICANT_PHRASES_TASW, 
	USELESS_COLLECTION;
	
}
